// Generated by CoffeeScript 1.9.2
module.exports = function(grunt) {
  var BUILD_PATH, html;
  BUILD_PATH = 'build';
  html = require('assets/js/tpl.js');
  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
    copy: {
      main: {
        files: [
          {
            src: ['./assets/**', '!./assets/**/*.coffee', '!./assets/**/*.map', '!./assets/libs/underscore.js', '!./assets/js/config.js', '!./assets/js/tpl.*', 'index-template.html', 'cache.manifest'],
            dest: BUILD_PATH + '/',
            filter: 'isFile',
            expand: true
          }
        ]
      }
    },
    clean: {
      options: {
        force: true
      },
      afterBuild: BUILD_PATH + "/index-template.html",
      beforeBuild: BUILD_PATH + "/"
    },
    replace: {
      options: {
        patterns: [
          {
            match: '$$APP_HTML$$',
            replacement: function() {
              return require('assets/js/tpl.js')();
            }
          }, {
            match: '$$TIMESTAMP$$',
            replacement: function() {
              return Date.now();
            }
          }
        ]
      },
      main: {
        src: BUILD_PATH + "/index-template.html",
        dest: BUILD_PATH + "/index.html"
      }
    }
  });
  grunt.loadNpmTasks('grunt-contrib-clean');
  grunt.loadNpmTasks('grunt-replace');
  grunt.loadNpmTasks('grunt-contrib-copy');
  return grunt.registerTask('default', ['clean:beforeBuild', 'copy', 'replace', 'clean:afterBuild']);
};
