# This is a basic workflow to help you get started with Actions

name: deploy pages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    # https://crontab.guru/
    # At 03:00 on Tuesday and Saturday.
    - cron: '0 3 * * 2,6'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '21.x'

    - name: set env
      if: github.event.schedule=='0 3 * * 2,6'
      run: |
        echo "IS_SCHEDULED=true" >> $GITHUB_ENV
    - name: install deps
      run: yarn

    - name: build site
      run: yarn build
      env:
        PEXELS_TOKEN: ${{ secrets.PEXELS_TOKEN }}
    - name: copy cname
      run: cp CNAME ./dist
    - name: Deploy to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@3.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        email: okarl@outlook.com
        branch: gh-pages   # optional
        build_dir: dist # folder the action should deploy.
        jekyll: no
